version:  '2'
services:
  mysql:
    image: percona:latest
    build: .docker/MYSQL
    volumes:
      - .docker/MYSQL/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:3306
    networks:
      - wimo
  node:
      build: .
      entrypoint:
            - /usr/local/bin/docker-entrypoint.sh
      depends_on:
            - mysql
      ports:
            - "3000:3000"
      networks:
        - wimo
networks:
    wimo:
      driver: bridge
  