version:  '3'
services:
  mysql:
    build: ./.docker/mysql
    volumes:
      - ./.docker/mysql/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:3306
    networks:
      - wimo
  node:
      build: ./.docker/node
      entrypoint:
            - /usr/local/bin/docker-entrypoint.sh
      depends_on:
            - mysql
      volumes:
            - "./:/app"
      ports:
            - "3000:3000"
      networks:
        - wimo
  nginx:
    build:
      context: ./.docker/nginx
    links:
      - node
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - "./client/dist:/usr/share/nginx/html"
  webpack:
    build: 
      context: ./.docker/webpack
    container_name: webpack
    volumes:
      - "./client:/app/client"
    command: "npm start"
networks:
    wimo:
      driver: bridge
